# Generated by Django 5.2.8 on 2025-12-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Optional. Can be duplicate. Users login with email.', max_length=150),
        ),
    ]
