# Generated by Django 5.2.8 on 2025-12-17 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Optional: Link product to a service (e.g., Screen Print, DTF)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.service'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['service', 'is_active'], name='catalog_pro_service_73274e_idx'),
        ),
    ]
