# Generated by Django 5.2.8 on 2025-12-19 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(default=0, help_text='Total quantity sold from completed orders', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
